kind: pipeline
type: docker
name: build and test
#Here we are installing and testing the code
steps:
  - name: backend
    image: node
    commands:
      - cd ./client/
      - npm ci
      - npm test

  - name: frontend
    image: node
    commands:
      - cd ./server/
      - npm ci
      - npm test

---
kind: pipeline
type: docker
name: CD
#here we are continuously delivering a version to docker hub, even if it's breaking.
steps:
  - name: build
    image: plugins/docker
    settings:
      enviroment:
        NODE_ENV: development
      registry:
        from secret: local_registry
      repo:
        from_secret: local_docker_repo
      username:
        from_secret: local_registry_username
      password:
        from_secret: local_docker_password
      dockerfile: Dockerfile
      tags:
        - DRONE_BUILD_NUMBER
        - latest
        - 1.1.0
