kind: pipeline
type: docker
name: CD
#here we are continuously delivering a version to docker hub, even if it's breaking.
steps:
  - name: publish
    image: plugins/docker
    settings:
      enviroment:
        NODE_ENV: development
      registry:
        from_secret: registry
      repo:
        from_secret: docker_repo
      username: destintech
      #        from_secret: registry_username
      password:
        from_secret: registry_password
      dockerfile: Dockerfile
      tags:
        - latest
        - 0.0.5
