kind: pipeline
type: docker
name: CI_CD

steps:
  - name: build
    image: plugins/docker
    settings:
      enviroment:
        NODE_ENV: development
      repo:
        from_secret: local_docker_repo
      username:
        from_secret: local_registry_username
      password:
        from_secret: local_docker_password
      dockerfile: Dockerfile
      tags:
        - "latest"
        - ["1.1.", DRONE_BUILD_NUMBER]

  - name: test
    image: node
    commands:
      - npm install
      - npm test

  - name: push_local
    image: plugins/docker
    settings:
      repo:
        from_secret: local_docker_repo
      registry:
        from secret: local_registry
      target: production
      enviroment:
        NODE_ENV: development
      tags:
        - "latest"
        - ["1.1.", DRONE_BUILD_NUMBER]
      username:
        from_secret: local_registry_username
      password:
        from_secret: local_docker_password
